services:
  front:
    build: ./thread-front
    ports:
      - "8089:80"
    depends_on:
      - back

  back:
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - bdd
    restart: always
    environment:
      JWT_SECRET: "uV8hR7xJm2QfA9pZs4KcT1nWb3LdE6yHq0GtP5vXoIrYjN8U"

  bdd:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: Thread_database
      MYSQL_ROOT_PASSWORD: root